#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v25
# autospec commit: 9594167
#
Name     : pacrunner
Version  : 0.19
Release  : 66
URL      : https://www.kernel.org/pub/linux/network/connman/pacrunner-0.19.tar.xz
Source0  : https://www.kernel.org/pub/linux/network/connman/pacrunner-0.19.tar.xz
Summary  : Proxy Configuration Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pacrunner-autostart = %{version}-%{release}
Requires: pacrunner-bin = %{version}-%{release}
Requires: pacrunner-config = %{version}-%{release}
Requires: pacrunner-data = %{version}-%{release}
Requires: pacrunner-license = %{version}-%{release}
Requires: pacrunner-services = %{version}-%{release}
BuildRequires : file
BuildRequires : flex-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libsystemd)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Update-pacrunner-dbus-config.patch
Patch2: 0002-Add-initial-systemd-service-file.patch
Patch3: 0003-Add-a-new-pacdiscovery-V2-service.patch
Patch4: 0004-Use-trimmed-down-glibc-C-locale.patch
Patch5: 0005-Add-port-stripping-for-FindProxyForURL.patch
Patch6: 0006-Don-t-print-out-pointers-for-no-reason.patch
Patch7: 0007-Write-out-wpad.dat-to-run-pacrunner-wpad.dat.patch
Patch8: 0008-Make-pacdiscovery-catch-network-changes.patch

%description
PACrunner - Proxy configuration daemon
**************************************
Compilation and installation
============================

%package autostart
Summary: autostart components for the pacrunner package.
Group: Default

%description autostart
autostart components for the pacrunner package.


%package bin
Summary: bin components for the pacrunner package.
Group: Binaries
Requires: pacrunner-data = %{version}-%{release}
Requires: pacrunner-config = %{version}-%{release}
Requires: pacrunner-license = %{version}-%{release}
Requires: pacrunner-services = %{version}-%{release}

%description bin
bin components for the pacrunner package.


%package config
Summary: config components for the pacrunner package.
Group: Default

%description config
config components for the pacrunner package.


%package data
Summary: data components for the pacrunner package.
Group: Data

%description data
data components for the pacrunner package.


%package license
Summary: license components for the pacrunner package.
Group: Default

%description license
license components for the pacrunner package.


%package services
Summary: services components for the pacrunner package.
Group: Systemd services
Requires: systemd

%description services
services components for the pacrunner package.


%prep
%setup -q -n pacrunner-0.19
cd %{_builddir}/pacrunner-0.19
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
pushd ..
cp -a pacrunner-0.19 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746735072
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --enable-duktape \
--disable-mozjs \
--enable-curl \
--enable-debug \
--disable-libproxy
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%reconfigure --disable-static --enable-duktape \
--disable-mozjs \
--enable-curl \
--enable-debug \
--disable-libproxy
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1746735072
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pacrunner
cp %{_builddir}/pacrunner-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pacrunner/a7a897a4bde987e597c04f16a9c28f6d3f57916d || :
cp %{_builddir}/pacrunner-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/pacrunner/32c7c5556c56cdbb2d507e27d28d081595a35a9b || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## service_restart content
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -s /usr/lib/systemd/system/pacdiscovery.service %{buildroot}/usr/share/clr-service-restart/pacdiscovery.service
ln -s /usr/lib/systemd/system/pacrunner.service %{buildroot}/usr/share/clr-service-restart/pacrunner.service
## service_restart end
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m644 src/pacrunner.service %{buildroot}/usr/lib/systemd/system/
install -m644 src/pacdiscovery.service %{buildroot}/usr/lib/systemd/system/
install -m644 src/pacdiscovery.path %{buildroot}/usr/lib/systemd/system/
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../pacdiscovery.path %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m644 src/pacdiscovery.conf %{buildroot}/usr/lib/tmpfiles.d/
mkdir -p %{buildroot}/usr/share/dbus-1/system.d
install -m644 src/pacrunner.conf %{buildroot}/usr/share/dbus-1/system.d/

rm -rf %{buildroot}/etc2
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/pacdiscovery.path

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pacdiscovery
/V3/usr/bin/pacrunner
/usr/bin/pacdiscovery
/usr/bin/pacrunner

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/pacdiscovery.conf

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/pacdiscovery.service
/usr/share/clr-service-restart/pacrunner.service
/usr/share/dbus-1/system-services/org.pacrunner.service
/usr/share/dbus-1/system.d/pacrunner.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pacrunner/32c7c5556c56cdbb2d507e27d28d081595a35a9b
/usr/share/package-licenses/pacrunner/a7a897a4bde987e597c04f16a9c28f6d3f57916d

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/pacdiscovery.path
/usr/lib/systemd/system/pacdiscovery.path
/usr/lib/systemd/system/pacdiscovery.service
/usr/lib/systemd/system/pacrunner.service
