#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pacrunner
Version  : 0.11
Release  : 32
URL      : https://www.kernel.org/pub/linux/network/connman/pacrunner-0.11.tar.xz
Source0  : https://www.kernel.org/pub/linux/network/connman/pacrunner-0.11.tar.xz
Summary  : Proxy Configuration Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pacrunner-bin
Requires: pacrunner-autostart
Requires: pacrunner-config
Requires: pacrunner-data
BuildRequires : flex-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libsystemd)
Patch1: 0001-dbus-Rename-D-Bus-autostart-service-file-name.patch
Patch2: 0002-Update-pacrunner-dbus-config.patch
Patch3: 0003-Add-initial-systemd-service-file.patch
Patch4: 0004-Add-a-new-pacdiscovery-service.patch
Patch5: 0005-Use-trimmed-down-glibc-C-locale.patch

%description
PACrunner - Proxy configuration daemon
**************************************
Compilation and installation
============================

%package autostart
Summary: autostart components for the pacrunner package.
Group: Default

%description autostart
autostart components for the pacrunner package.


%package bin
Summary: bin components for the pacrunner package.
Group: Binaries
Requires: pacrunner-data
Requires: pacrunner-config

%description bin
bin components for the pacrunner package.


%package config
Summary: config components for the pacrunner package.
Group: Default

%description config
config components for the pacrunner package.


%package data
Summary: data components for the pacrunner package.
Group: Data

%description data
data components for the pacrunner package.


%prep
%setup -q -n pacrunner-0.11
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500945968
%reconfigure --disable-static --enable-duktape \
--disable-mozjs \
--enable-curl \
--enable-debug
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1500945968
rm -rf %{buildroot}
%make_install
## make_install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m644 src/pacrunner.service %{buildroot}/usr/lib/systemd/system/
install -m644 src/pacdiscovery.service %{buildroot}/usr/lib/systemd/system/
install -m644 src/pacdiscovery.path %{buildroot}/usr/lib/systemd/system/
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../pacdiscovery.path %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m644 src/pacdiscovery.conf %{buildroot}/usr/lib/tmpfiles.d/
mkdir -p %{buildroot}/usr/share/dbus-1/system.d
install -m644 src/pacrunner.conf %{buildroot}/usr/share/dbus-1/system.d/
## make_install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/pacdiscovery.path

%files bin
%defattr(-,root,root,-)
/usr/bin/pacdiscovery
/usr/bin/pacrunner

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/pacdiscovery.path
/usr/lib/systemd/system/pacdiscovery.path
/usr/lib/systemd/system/pacdiscovery.service
/usr/lib/systemd/system/pacrunner.service
/usr/lib/tmpfiles.d/pacdiscovery.conf

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.pacrunner.service
/usr/share/dbus-1/system.d/pacrunner.conf
